# Application name = E_VEDA-API
spring.application.name=E_VEDA-API

# Setting to play nicely with swagger and tomcat
server.forward-headers-strategy=framework

# To run on localhost-8081 port
server.port=8081
