// proto/user.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: userpb/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_userpb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_userpb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_userpb_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UploadProfilePictureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`       // e.g., "image/jpeg" or "image/png"
	FileExtension string                 `protobuf:"bytes,4,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"` // e.g., ".jpg"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProfilePictureRequest) Reset() {
	*x = UploadProfilePictureRequest{}
	mi := &file_userpb_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProfilePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfilePictureRequest) ProtoMessage() {}

func (x *UploadProfilePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfilePictureRequest.ProtoReflect.Descriptor instead.
func (*UploadProfilePictureRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{3}
}

func (x *UploadProfilePictureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadProfilePictureRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadProfilePictureRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadProfilePictureRequest) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

type ProfileUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age           int64                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Height        int64                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdateRequest) Reset() {
	*x = ProfileUpdateRequest{}
	mi := &file_userpb_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdateRequest) ProtoMessage() {}

func (x *ProfileUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProfileUpdateRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileUpdateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileUpdateRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileUpdateRequest) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *ProfileUpdateRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProfileUpdateRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProfileUpdateRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type GetGlobalTrendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalTrendsRequest) Reset() {
	*x = GetGlobalTrendsRequest{}
	mi := &file_userpb_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalTrendsRequest) ProtoMessage() {}

func (x *GetGlobalTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalTrendsRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalTrendsRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{5}
}

type DailyEmotion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`   // e.g., "MON", "TUE"
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // e.g., "2026-04-12"
	Joy           float64                `protobuf:"fixed64,3,opt,name=joy,proto3" json:"joy,omitempty"`
	Anger         float64                `protobuf:"fixed64,4,opt,name=anger,proto3" json:"anger,omitempty"`
	Sadness       float64                `protobuf:"fixed64,5,opt,name=sadness,proto3" json:"sadness,omitempty"`
	Fear          float64                `protobuf:"fixed64,6,opt,name=fear,proto3" json:"fear,omitempty"`
	Surprise      float64                `protobuf:"fixed64,7,opt,name=surprise,proto3" json:"surprise,omitempty"`
	Disgust       float64                `protobuf:"fixed64,8,opt,name=disgust,proto3" json:"disgust,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyEmotion) Reset() {
	*x = DailyEmotion{}
	mi := &file_userpb_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyEmotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyEmotion) ProtoMessage() {}

func (x *DailyEmotion) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyEmotion.ProtoReflect.Descriptor instead.
func (*DailyEmotion) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{6}
}

func (x *DailyEmotion) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DailyEmotion) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyEmotion) GetJoy() float64 {
	if x != nil {
		return x.Joy
	}
	return 0
}

func (x *DailyEmotion) GetAnger() float64 {
	if x != nil {
		return x.Anger
	}
	return 0
}

func (x *DailyEmotion) GetSadness() float64 {
	if x != nil {
		return x.Sadness
	}
	return 0
}

func (x *DailyEmotion) GetFear() float64 {
	if x != nil {
		return x.Fear
	}
	return 0
}

func (x *DailyEmotion) GetSurprise() float64 {
	if x != nil {
		return x.Surprise
	}
	return 0
}

func (x *DailyEmotion) GetDisgust() float64 {
	if x != nil {
		return x.Disgust
	}
	return 0
}

type CreateNewReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,3,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewReportRequest) Reset() {
	*x = CreateNewReportRequest{}
	mi := &file_userpb_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewReportRequest) ProtoMessage() {}

func (x *CreateNewReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewReportRequest.ProtoReflect.Descriptor instead.
func (*CreateNewReportRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{7}
}

func (x *CreateNewReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *CreateNewReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNewReportRequest) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *CreateNewReportRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type UserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nickname       string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age            int64                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,4,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	Height         int64                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Weight         float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Gender         string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_userpb_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserResponse) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserResponse) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *UserResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UserResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UserResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type ProfileCompletenessResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IsCompleted         bool                   `protobuf:"varint,1,opt,name=isCompleted,proto3" json:"isCompleted,omitempty"`
	PercentageCompleted float64                `protobuf:"fixed64,2,opt,name=percentage_completed,json=percentageCompleted,proto3" json:"percentage_completed,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProfileCompletenessResponse) Reset() {
	*x = ProfileCompletenessResponse{}
	mi := &file_userpb_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileCompletenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileCompletenessResponse) ProtoMessage() {}

func (x *ProfileCompletenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileCompletenessResponse.ProtoReflect.Descriptor instead.
func (*ProfileCompletenessResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{9}
}

func (x *ProfileCompletenessResponse) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *ProfileCompletenessResponse) GetPercentageCompleted() float64 {
	if x != nil {
		return x.PercentageCompleted
	}
	return 0
}

func (x *ProfileCompletenessResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NameAndPictureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,2,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NameAndPictureResponse) Reset() {
	*x = NameAndPictureResponse{}
	mi := &file_userpb_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameAndPictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameAndPictureResponse) ProtoMessage() {}

func (x *NameAndPictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameAndPictureResponse.ProtoReflect.Descriptor instead.
func (*NameAndPictureResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{10}
}

func (x *NameAndPictureResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NameAndPictureResponse) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

type GetEmotionalTrendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trends        []*DailyEmotion        `protobuf:"bytes,1,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmotionalTrendsResponse) Reset() {
	*x = GetEmotionalTrendsResponse{}
	mi := &file_userpb_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmotionalTrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmotionalTrendsResponse) ProtoMessage() {}

func (x *GetEmotionalTrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmotionalTrendsResponse.ProtoReflect.Descriptor instead.
func (*GetEmotionalTrendsResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetEmotionalTrendsResponse) GetTrends() []*DailyEmotion {
	if x != nil {
		return x.Trends
	}
	return nil
}

type GetDailyInsightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Insight       string                 `protobuf:"bytes,1,opt,name=insight,proto3" json:"insight,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"` // ADD THIS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyInsightResponse) Reset() {
	*x = GetDailyInsightResponse{}
	mi := &file_userpb_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyInsightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyInsightResponse) ProtoMessage() {}

func (x *GetDailyInsightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyInsightResponse.ProtoReflect.Descriptor instead.
func (*GetDailyInsightResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetDailyInsightResponse) GetInsight() string {
	if x != nil {
		return x.Insight
	}
	return ""
}

func (x *GetDailyInsightResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_userpb_user_proto protoreflect.FileDescriptor

const file_userpb_user_proto_rawDesc = "" +
	"\n" +
	"\x11userpb/user.proto\x12\x04user\"@\n" +
	"\x11CreateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"'\n" +
	"\vApiResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9d\x01\n" +
	"\x1bUploadProfilePictureRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12%\n" +
	"\x0efile_extension\x18\x04 \x01(\tR\rfileExtension\"\xb9\x01\n" +
	"\x14ProfileUpdateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x03R\x03age\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x03R\x06height\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\"\x18\n" +
	"\x16GetGlobalTrendsRequest\"\xc0\x01\n" +
	"\fDailyEmotion\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x10\n" +
	"\x03joy\x18\x03 \x01(\x01R\x03joy\x12\x14\n" +
	"\x05anger\x18\x04 \x01(\x01R\x05anger\x12\x18\n" +
	"\asadness\x18\x05 \x01(\x01R\asadness\x12\x12\n" +
	"\x04fear\x18\x06 \x01(\x01R\x04fear\x12\x1a\n" +
	"\bsurprise\x18\a \x01(\x01R\bsurprise\x12\x18\n" +
	"\adisgust\x18\b \x01(\x01R\adisgust\"\x88\x01\n" +
	"\x16CreateNewReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\taudio_url\x18\x03 \x01(\tR\baudioUrl\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\"\xc1\x01\n" +
	"\fUserResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x03R\x03age\x12'\n" +
	"\x0fprofile_picture\x18\x04 \x01(\tR\x0eprofilePicture\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x03R\x06height\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\"\x86\x01\n" +
	"\x1bProfileCompletenessResponse\x12 \n" +
	"\visCompleted\x18\x01 \x01(\bR\visCompleted\x121\n" +
	"\x14percentage_completed\x18\x02 \x01(\x01R\x13percentageCompleted\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"U\n" +
	"\x16NameAndPictureResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fprofile_picture\x18\x02 \x01(\tR\x0eprofilePicture\"H\n" +
	"\x1aGetEmotionalTrendsResponse\x12*\n" +
	"\x06trends\x18\x01 \x03(\v2\x12.user.DailyEmotionR\x06trends\"M\n" +
	"\x17GetDailyInsightResponse\x12\x18\n" +
	"\ainsight\x18\x01 \x01(\tR\ainsight\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails2\x92\x06\n" +
	"\vUserService\x128\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x11.user.ApiResponse\x123\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponse\x12;\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.ProfileUpdateRequest\x1a\x11.user.ApiResponse\x12L\n" +
	"\x14UploadProfilePicture\x12!.user.UploadProfilePictureRequest\x1a\x11.user.ApiResponse\x12Q\n" +
	"\x16GetProfileCompleteness\x12\x14.user.GetUserRequest\x1a!.user.ProfileCompletenessResponse\x12G\n" +
	"\x11GetPictureAndName\x12\x14.user.GetUserRequest\x1a\x1c.user.NameAndPictureResponse\x12Z\n" +
	"\x18GetGlobalEmotionalTrends\x12\x1c.user.GetGlobalTrendsRequest\x1a .user.GetEmotionalTrendsResponse\x12F\n" +
	"\x0fGetDailyInsight\x12\x14.user.GetUserRequest\x1a\x1d.user.GetDailyInsightResponse\x12C\n" +
	"\vUploadAudio\x12!.user.UploadProfilePictureRequest\x1a\x11.user.ApiResponse\x12C\n" +
	"\vUploadVideo\x12!.user.UploadProfilePictureRequest\x1a\x11.user.ApiResponse\x12?\n" +
	"\fCreateReport\x12\x1c.user.CreateNewReportRequest\x1a\x11.user.ApiResponseB\x15Z\x13e_veda/proto/userpbb\x06proto3"

var (
	file_userpb_user_proto_rawDescOnce sync.Once
	file_userpb_user_proto_rawDescData []byte
)

func file_userpb_user_proto_rawDescGZIP() []byte {
	file_userpb_user_proto_rawDescOnce.Do(func() {
		file_userpb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userpb_user_proto_rawDesc), len(file_userpb_user_proto_rawDesc)))
	})
	return file_userpb_user_proto_rawDescData
}

var file_userpb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_userpb_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),           // 0: user.CreateUserRequest
	(*ApiResponse)(nil),                 // 1: user.ApiResponse
	(*GetUserRequest)(nil),              // 2: user.GetUserRequest
	(*UploadProfilePictureRequest)(nil), // 3: user.UploadProfilePictureRequest
	(*ProfileUpdateRequest)(nil),        // 4: user.ProfileUpdateRequest
	(*GetGlobalTrendsRequest)(nil),      // 5: user.GetGlobalTrendsRequest
	(*DailyEmotion)(nil),                // 6: user.DailyEmotion
	(*CreateNewReportRequest)(nil),      // 7: user.CreateNewReportRequest
	(*UserResponse)(nil),                // 8: user.UserResponse
	(*ProfileCompletenessResponse)(nil), // 9: user.ProfileCompletenessResponse
	(*NameAndPictureResponse)(nil),      // 10: user.NameAndPictureResponse
	(*GetEmotionalTrendsResponse)(nil),  // 11: user.GetEmotionalTrendsResponse
	(*GetDailyInsightResponse)(nil),     // 12: user.GetDailyInsightResponse
}
var file_userpb_user_proto_depIdxs = []int32{
	6,  // 0: user.GetEmotionalTrendsResponse.trends:type_name -> user.DailyEmotion
	0,  // 1: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	2,  // 2: user.UserService.GetUser:input_type -> user.GetUserRequest
	4,  // 3: user.UserService.UpdateUser:input_type -> user.ProfileUpdateRequest
	3,  // 4: user.UserService.UploadProfilePicture:input_type -> user.UploadProfilePictureRequest
	2,  // 5: user.UserService.GetProfileCompleteness:input_type -> user.GetUserRequest
	2,  // 6: user.UserService.GetPictureAndName:input_type -> user.GetUserRequest
	5,  // 7: user.UserService.GetGlobalEmotionalTrends:input_type -> user.GetGlobalTrendsRequest
	2,  // 8: user.UserService.GetDailyInsight:input_type -> user.GetUserRequest
	3,  // 9: user.UserService.UploadAudio:input_type -> user.UploadProfilePictureRequest
	3,  // 10: user.UserService.UploadVideo:input_type -> user.UploadProfilePictureRequest
	7,  // 11: user.UserService.CreateReport:input_type -> user.CreateNewReportRequest
	1,  // 12: user.UserService.CreateUser:output_type -> user.ApiResponse
	8,  // 13: user.UserService.GetUser:output_type -> user.UserResponse
	1,  // 14: user.UserService.UpdateUser:output_type -> user.ApiResponse
	1,  // 15: user.UserService.UploadProfilePicture:output_type -> user.ApiResponse
	9,  // 16: user.UserService.GetProfileCompleteness:output_type -> user.ProfileCompletenessResponse
	10, // 17: user.UserService.GetPictureAndName:output_type -> user.NameAndPictureResponse
	11, // 18: user.UserService.GetGlobalEmotionalTrends:output_type -> user.GetEmotionalTrendsResponse
	12, // 19: user.UserService.GetDailyInsight:output_type -> user.GetDailyInsightResponse
	1,  // 20: user.UserService.UploadAudio:output_type -> user.ApiResponse
	1,  // 21: user.UserService.UploadVideo:output_type -> user.ApiResponse
	1,  // 22: user.UserService.CreateReport:output_type -> user.ApiResponse
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_userpb_user_proto_init() }
func file_userpb_user_proto_init() {
	if File_userpb_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userpb_user_proto_rawDesc), len(file_userpb_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userpb_user_proto_goTypes,
		DependencyIndexes: file_userpb_user_proto_depIdxs,
		MessageInfos:      file_userpb_user_proto_msgTypes,
	}.Build()
	File_userpb_user_proto = out.File
	file_userpb_user_proto_goTypes = nil
	file_userpb_user_proto_depIdxs = nil
}
