// proto/user.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: userpb/user.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CreateUser_FullMethodName               = "/user.UserService/CreateUser"
	UserService_GetUser_FullMethodName                  = "/user.UserService/GetUser"
	UserService_UpdateUser_FullMethodName               = "/user.UserService/UpdateUser"
	UserService_UploadProfilePicture_FullMethodName     = "/user.UserService/UploadProfilePicture"
	UserService_GetProfileCompleteness_FullMethodName   = "/user.UserService/GetProfileCompleteness"
	UserService_GetPictureAndName_FullMethodName        = "/user.UserService/GetPictureAndName"
	UserService_GetGlobalEmotionalTrends_FullMethodName = "/user.UserService/GetGlobalEmotionalTrends"
	UserService_GetDailyInsight_FullMethodName          = "/user.UserService/GetDailyInsight"
	UserService_UploadAudio_FullMethodName              = "/user.UserService/UploadAudio"
	UserService_UploadVideo_FullMethodName              = "/user.UserService/UploadVideo"
	UserService_CreateNewReport_FullMethodName          = "/user.UserService/CreateNewReport"
	UserService_GetReportsList_FullMethodName           = "/user.UserService/GetReportsList"
	UserService_GetReportDraftInfo_FullMethodName       = "/user.UserService/GetReportDraftInfo"
	UserService_GetReportByID_FullMethodName            = "/user.UserService/GetReportByID"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	UpdateUser(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	UploadProfilePicture(ctx context.Context, in *UploadProfilePictureRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	GetProfileCompleteness(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*ProfileCompletenessResponse, error)
	GetPictureAndName(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*NameAndPictureResponse, error)
	GetGlobalEmotionalTrends(ctx context.Context, in *GetGlobalTrendsRequest, opts ...grpc.CallOption) (*GetEmotionalTrendsResponse, error)
	GetDailyInsight(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetDailyInsightResponse, error)
	UploadAudio(ctx context.Context, in *UploadProfilePictureRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	UploadVideo(ctx context.Context, in *UploadProfilePictureRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	CreateNewReport(ctx context.Context, in *CreateNewReportRequest, opts ...grpc.CallOption) (*ReportGeneratedResponse, error)
	GetReportsList(ctx context.Context, in *GetReportsListRequest, opts ...grpc.CallOption) (*GetReportsListResponse, error)
	GetReportDraftInfo(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetReportDraftInfoResponse, error)
	GetReportByID(ctx context.Context, in *GetReportByIdRequest, opts ...grpc.CallOption) (*GetReportDetailsResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UploadProfilePicture(ctx context.Context, in *UploadProfilePictureRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_UploadProfilePicture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetProfileCompleteness(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*ProfileCompletenessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileCompletenessResponse)
	err := c.cc.Invoke(ctx, UserService_GetProfileCompleteness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPictureAndName(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*NameAndPictureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameAndPictureResponse)
	err := c.cc.Invoke(ctx, UserService_GetPictureAndName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetGlobalEmotionalTrends(ctx context.Context, in *GetGlobalTrendsRequest, opts ...grpc.CallOption) (*GetEmotionalTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmotionalTrendsResponse)
	err := c.cc.Invoke(ctx, UserService_GetGlobalEmotionalTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetDailyInsight(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetDailyInsightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyInsightResponse)
	err := c.cc.Invoke(ctx, UserService_GetDailyInsight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UploadAudio(ctx context.Context, in *UploadProfilePictureRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_UploadAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UploadVideo(ctx context.Context, in *UploadProfilePictureRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, UserService_UploadVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateNewReport(ctx context.Context, in *CreateNewReportRequest, opts ...grpc.CallOption) (*ReportGeneratedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportGeneratedResponse)
	err := c.cc.Invoke(ctx, UserService_CreateNewReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetReportsList(ctx context.Context, in *GetReportsListRequest, opts ...grpc.CallOption) (*GetReportsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReportsListResponse)
	err := c.cc.Invoke(ctx, UserService_GetReportsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetReportDraftInfo(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetReportDraftInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReportDraftInfoResponse)
	err := c.cc.Invoke(ctx, UserService_GetReportDraftInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetReportByID(ctx context.Context, in *GetReportByIdRequest, opts ...grpc.CallOption) (*GetReportDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReportDetailsResponse)
	err := c.cc.Invoke(ctx, UserService_GetReportByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*ApiResponse, error)
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	UpdateUser(context.Context, *ProfileUpdateRequest) (*ApiResponse, error)
	UploadProfilePicture(context.Context, *UploadProfilePictureRequest) (*ApiResponse, error)
	GetProfileCompleteness(context.Context, *GetUserRequest) (*ProfileCompletenessResponse, error)
	GetPictureAndName(context.Context, *GetUserRequest) (*NameAndPictureResponse, error)
	GetGlobalEmotionalTrends(context.Context, *GetGlobalTrendsRequest) (*GetEmotionalTrendsResponse, error)
	GetDailyInsight(context.Context, *GetUserRequest) (*GetDailyInsightResponse, error)
	UploadAudio(context.Context, *UploadProfilePictureRequest) (*ApiResponse, error)
	UploadVideo(context.Context, *UploadProfilePictureRequest) (*ApiResponse, error)
	CreateNewReport(context.Context, *CreateNewReportRequest) (*ReportGeneratedResponse, error)
	GetReportsList(context.Context, *GetReportsListRequest) (*GetReportsListResponse, error)
	GetReportDraftInfo(context.Context, *GetUserRequest) (*GetReportDraftInfoResponse, error)
	GetReportByID(context.Context, *GetReportByIdRequest) (*GetReportDetailsResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *ProfileUpdateRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServiceServer) UploadProfilePicture(context.Context, *UploadProfilePictureRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadProfilePicture not implemented")
}
func (UnimplementedUserServiceServer) GetProfileCompleteness(context.Context, *GetUserRequest) (*ProfileCompletenessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfileCompleteness not implemented")
}
func (UnimplementedUserServiceServer) GetPictureAndName(context.Context, *GetUserRequest) (*NameAndPictureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPictureAndName not implemented")
}
func (UnimplementedUserServiceServer) GetGlobalEmotionalTrends(context.Context, *GetGlobalTrendsRequest) (*GetEmotionalTrendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalEmotionalTrends not implemented")
}
func (UnimplementedUserServiceServer) GetDailyInsight(context.Context, *GetUserRequest) (*GetDailyInsightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyInsight not implemented")
}
func (UnimplementedUserServiceServer) UploadAudio(context.Context, *UploadProfilePictureRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAudio not implemented")
}
func (UnimplementedUserServiceServer) UploadVideo(context.Context, *UploadProfilePictureRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedUserServiceServer) CreateNewReport(context.Context, *CreateNewReportRequest) (*ReportGeneratedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewReport not implemented")
}
func (UnimplementedUserServiceServer) GetReportsList(context.Context, *GetReportsListRequest) (*GetReportsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReportsList not implemented")
}
func (UnimplementedUserServiceServer) GetReportDraftInfo(context.Context, *GetUserRequest) (*GetReportDraftInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReportDraftInfo not implemented")
}
func (UnimplementedUserServiceServer) GetReportByID(context.Context, *GetReportByIdRequest) (*GetReportDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReportByID not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*ProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UploadProfilePicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadProfilePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UploadProfilePicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UploadProfilePicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UploadProfilePicture(ctx, req.(*UploadProfilePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetProfileCompleteness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProfileCompleteness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetProfileCompleteness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProfileCompleteness(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPictureAndName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPictureAndName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPictureAndName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPictureAndName(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetGlobalEmotionalTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetGlobalEmotionalTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetGlobalEmotionalTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetGlobalEmotionalTrends(ctx, req.(*GetGlobalTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetDailyInsight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetDailyInsight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetDailyInsight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetDailyInsight(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UploadAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadProfilePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UploadAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UploadAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UploadAudio(ctx, req.(*UploadProfilePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UploadVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadProfilePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UploadVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UploadVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UploadVideo(ctx, req.(*UploadProfilePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateNewReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateNewReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateNewReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateNewReport(ctx, req.(*CreateNewReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetReportsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetReportsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetReportsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetReportsList(ctx, req.(*GetReportsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetReportDraftInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetReportDraftInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetReportDraftInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetReportDraftInfo(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetReportByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetReportByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetReportByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetReportByID(ctx, req.(*GetReportByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "UploadProfilePicture",
			Handler:    _UserService_UploadProfilePicture_Handler,
		},
		{
			MethodName: "GetProfileCompleteness",
			Handler:    _UserService_GetProfileCompleteness_Handler,
		},
		{
			MethodName: "GetPictureAndName",
			Handler:    _UserService_GetPictureAndName_Handler,
		},
		{
			MethodName: "GetGlobalEmotionalTrends",
			Handler:    _UserService_GetGlobalEmotionalTrends_Handler,
		},
		{
			MethodName: "GetDailyInsight",
			Handler:    _UserService_GetDailyInsight_Handler,
		},
		{
			MethodName: "UploadAudio",
			Handler:    _UserService_UploadAudio_Handler,
		},
		{
			MethodName: "UploadVideo",
			Handler:    _UserService_UploadVideo_Handler,
		},
		{
			MethodName: "CreateNewReport",
			Handler:    _UserService_CreateNewReport_Handler,
		},
		{
			MethodName: "GetReportsList",
			Handler:    _UserService_GetReportsList_Handler,
		},
		{
			MethodName: "GetReportDraftInfo",
			Handler:    _UserService_GetReportDraftInfo_Handler,
		},
		{
			MethodName: "GetReportByID",
			Handler:    _UserService_GetReportByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userpb/user.proto",
}
