// proto/user.proto
syntax = "proto3";
package user;
option go_package = "e_veda/proto/userpb";

service UserService {
  rpc CreateUser (CreateUserRequest) returns (ApiResponse);
  rpc GetUser (GetUserRequest) returns (UserResponse);
  rpc UpdateUser (ProfileUpdateRequest) returns (ApiResponse);
  rpc UploadProfilePicture (UploadProfilePictureRequest) returns (ApiResponse);
  rpc GetProfileCompleteness(GetUserRequest) returns (ProfileCompletenessResponse) ;
  rpc GetPictureAndName (GetUserRequest) returns (NameAndPictureResponse);
  rpc GetGlobalEmotionalTrends (GetGlobalTrendsRequest) returns (GetEmotionalTrendsResponse);
  rpc GetDailyInsight (GetUserRequest) returns (GetDailyInsightResponse);
  rpc UploadAudio (UploadProfilePictureRequest) returns (ApiResponse);
  rpc UploadVideo (UploadProfilePictureRequest) returns (ApiResponse);
  rpc CreateNewReport (CreateNewReportRequest) returns (ReportGeneratedResponse);
  rpc GetReportsList (GetReportsListRequest) returns (GetReportsListResponse);
  rpc GetReportDraftInfo (GetUserRequest) returns (GetReportDraftInfoResponse);
}

message CreateUserRequest {
  string user_id = 1;
  string name = 2;
}

message ApiResponse {
  string message = 1;
}

message GetUserRequest {
  string user_id = 1;
}

message UploadProfilePictureRequest {
  string user_id = 1;
  bytes file_data = 2;
  string content_type = 3; // e.g., "image/jpeg" or "image/png"
  string file_extension = 4; // e.g., ".jpg"
}


message ProfileUpdateRequest {
  string user_id = 1;
  string name = 2;
  string nickname = 3;
  int64 age = 4;
  int64 height = 5;
  double weight = 6;
  string gender = 7;
}

message GetGlobalTrendsRequest {}

message CreateNewReportRequest {
  string user_id = 1;
  string audio_url = 2;
  string video_url = 3;
}

message GetReportsListRequest {
  string user_id = 1;
  int32 page = 2;
  int32 limit = 3;
  string search_query = 4; // To power the "Search patient data..." bar
}

message DailyEmotion {
  string day = 1;       // e.g., "MON", "TUE"
  string date = 2;      // e.g., "2026-04-12"
  double joy = 3;
  double anger = 4;
  double sadness = 5;
  double fear = 6;
  double surprise = 7;
  double disgust = 8;
}

message ReportSummary {
  string id = 1;
  string patient_name = 2;
  string date = 3;
  string report_type = 4;
  string status = 5;
  string time = 6;
  optional double accuracy_rate = 7;
  optional double confidence_rate = 8;
  optional string analysis_result = 9;
}

message ResultAnalysis {
  string emotion_1_name = 1;
  double emotion_1_rating = 2;
  string emotion_2_name = 3;
  double emotion_2_rating = 4;
  string eye_movement = 5;
  string voice_tension = 6;
  string blink_frequency = 7;
  double accuracy_rate = 8;
  double confidence_rate = 9;
}

message AiSummary {
  string summary = 1;
}

message AiRecommendations{
  string point_1_title = 1;
  string point_1_description = 2;
  string point_2_title = 3;
  string point_2_description = 4;
}

message UserResponse {
  string name = 1;
  string nickname = 2;
  int64 age = 3;
  string profile_picture = 4;
  int64 height = 5;
  double weight = 6;
  string gender = 7;
}

message ProfileCompletenessResponse {
  bool isCompleted = 1;
  double percentage_completed = 2;
  string name = 3;
}

message NameAndPictureResponse {
  string name = 1;
  string profile_picture = 2;
}

message GetEmotionalTrendsResponse {
  repeated DailyEmotion trends = 1;
}

message GetDailyInsightResponse {
  string insight = 1;
  string details = 2; // ADD THIS
}

message GetReportsListResponse {
  repeated ReportSummary reports = 1;
  int32 total_count = 2;
  int32 total_pages = 3;
  int32 current_page = 4;
}

message GetReportDraftInfoResponse {
  string patient_name = 1;
  string projected_next_id = 2; // We call it 'projected' because it might change!
}

message ReportGeneratedResponse {
  ResultAnalysis result_analysis = 1;
  AiSummary ai_summary = 2;
  AiRecommendations ai_recommendations = 3;
  string message = 4;
}