// proto/user.proto
syntax = "proto3";
package user;
option go_package = "e_veda/proto/userpb";

service UserService {
  rpc CreateUser (CreateUserRequest) returns (ApiResponse);
  rpc GetUser (GetUserRequest) returns (UserResponse);
  rpc UpdateUser (ProfileUpdateRequest) returns (ApiResponse);
  rpc UploadProfilePicture (UploadProfilePictureRequest) returns (ApiResponse);
  rpc GetProfileCompleteness(GetUserRequest) returns (ProfileCompletenessResponse) ;
}

message CreateUserRequest {
  string user_id = 1;
  string name = 2;
}

message ApiResponse {
  string message = 1;
}

message GetUserRequest {
  string user_id = 1;
}

message UploadProfilePictureRequest {
  string user_id = 1;
  bytes file_data = 2;
  string content_type = 3; // e.g., "image/jpeg" or "image/png"
  string file_extension = 4; // e.g., ".jpg"
}

message ProfileUpdateRequest {
  string user_id = 1;
  string name = 2;
  string nickname = 3;
  int64 age = 4;
}

message UserResponse {
  string name = 1;
  string nickname = 2;
  int64 age = 3;
  string profile_picture = 4;
}

message ProfileCompletenessResponse {
  bool isCompleted = 1;
  double percentage_completed = 2;
  string name = 3;
}