// proto/user.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: userpb/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_userpb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_userpb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_userpb_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UploadProfilePictureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`       // e.g., "image/jpeg" or "image/png"
	FileExtension string                 `protobuf:"bytes,4,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"` // e.g., ".jpg"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProfilePictureRequest) Reset() {
	*x = UploadProfilePictureRequest{}
	mi := &file_userpb_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProfilePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfilePictureRequest) ProtoMessage() {}

func (x *UploadProfilePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfilePictureRequest.ProtoReflect.Descriptor instead.
func (*UploadProfilePictureRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{3}
}

func (x *UploadProfilePictureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadProfilePictureRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadProfilePictureRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadProfilePictureRequest) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

type ProfileUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age           int64                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Height        int64                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdateRequest) Reset() {
	*x = ProfileUpdateRequest{}
	mi := &file_userpb_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdateRequest) ProtoMessage() {}

func (x *ProfileUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProfileUpdateRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileUpdateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileUpdateRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileUpdateRequest) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *ProfileUpdateRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProfileUpdateRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProfileUpdateRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type GetGlobalTrendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalTrendsRequest) Reset() {
	*x = GetGlobalTrendsRequest{}
	mi := &file_userpb_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalTrendsRequest) ProtoMessage() {}

func (x *GetGlobalTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalTrendsRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalTrendsRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{5}
}

type CreateNewReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,2,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,3,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewReportRequest) Reset() {
	*x = CreateNewReportRequest{}
	mi := &file_userpb_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewReportRequest) ProtoMessage() {}

func (x *CreateNewReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewReportRequest.ProtoReflect.Descriptor instead.
func (*CreateNewReportRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNewReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNewReportRequest) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *CreateNewReportRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type GetReportByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportByIdRequest) Reset() {
	*x = GetReportByIdRequest{}
	mi := &file_userpb_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportByIdRequest) ProtoMessage() {}

func (x *GetReportByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportByIdRequest.ProtoReflect.Descriptor instead.
func (*GetReportByIdRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetReportByIdRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type GetReportsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,4,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"` // To power the "Search patient data..." bar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportsListRequest) Reset() {
	*x = GetReportsListRequest{}
	mi := &file_userpb_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportsListRequest) ProtoMessage() {}

func (x *GetReportsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportsListRequest.ProtoReflect.Descriptor instead.
func (*GetReportsListRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetReportsListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetReportsListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetReportsListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetReportsListRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type DailyEmotion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`   // e.g., "MON", "TUE"
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // e.g., "2026-04-12"
	Joy           float64                `protobuf:"fixed64,3,opt,name=joy,proto3" json:"joy,omitempty"`
	Anger         float64                `protobuf:"fixed64,4,opt,name=anger,proto3" json:"anger,omitempty"`
	Sadness       float64                `protobuf:"fixed64,5,opt,name=sadness,proto3" json:"sadness,omitempty"`
	Fear          float64                `protobuf:"fixed64,6,opt,name=fear,proto3" json:"fear,omitempty"`
	Surprise      float64                `protobuf:"fixed64,7,opt,name=surprise,proto3" json:"surprise,omitempty"`
	Disgust       float64                `protobuf:"fixed64,8,opt,name=disgust,proto3" json:"disgust,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyEmotion) Reset() {
	*x = DailyEmotion{}
	mi := &file_userpb_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyEmotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyEmotion) ProtoMessage() {}

func (x *DailyEmotion) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyEmotion.ProtoReflect.Descriptor instead.
func (*DailyEmotion) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{9}
}

func (x *DailyEmotion) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DailyEmotion) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyEmotion) GetJoy() float64 {
	if x != nil {
		return x.Joy
	}
	return 0
}

func (x *DailyEmotion) GetAnger() float64 {
	if x != nil {
		return x.Anger
	}
	return 0
}

func (x *DailyEmotion) GetSadness() float64 {
	if x != nil {
		return x.Sadness
	}
	return 0
}

func (x *DailyEmotion) GetFear() float64 {
	if x != nil {
		return x.Fear
	}
	return 0
}

func (x *DailyEmotion) GetSurprise() float64 {
	if x != nil {
		return x.Surprise
	}
	return 0
}

func (x *DailyEmotion) GetDisgust() float64 {
	if x != nil {
		return x.Disgust
	}
	return 0
}

type ReportSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientName    string                 `protobuf:"bytes,2,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	Date           string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	ReportType     string                 `protobuf:"bytes,4,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Time           string                 `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	AccuracyRate   *float64               `protobuf:"fixed64,7,opt,name=accuracy_rate,json=accuracyRate,proto3,oneof" json:"accuracy_rate,omitempty"`
	ConfidenceRate *float64               `protobuf:"fixed64,8,opt,name=confidence_rate,json=confidenceRate,proto3,oneof" json:"confidence_rate,omitempty"`
	AnalysisResult *string                `protobuf:"bytes,9,opt,name=analysis_result,json=analysisResult,proto3,oneof" json:"analysis_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportSummary) Reset() {
	*x = ReportSummary{}
	mi := &file_userpb_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSummary) ProtoMessage() {}

func (x *ReportSummary) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSummary.ProtoReflect.Descriptor instead.
func (*ReportSummary) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{10}
}

func (x *ReportSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportSummary) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *ReportSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ReportSummary) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *ReportSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportSummary) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ReportSummary) GetAccuracyRate() float64 {
	if x != nil && x.AccuracyRate != nil {
		return *x.AccuracyRate
	}
	return 0
}

func (x *ReportSummary) GetConfidenceRate() float64 {
	if x != nil && x.ConfidenceRate != nil {
		return *x.ConfidenceRate
	}
	return 0
}

func (x *ReportSummary) GetAnalysisResult() string {
	if x != nil && x.AnalysisResult != nil {
		return *x.AnalysisResult
	}
	return ""
}

type ResultAnalysis struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Emotion_1Name   string                 `protobuf:"bytes,1,opt,name=emotion_1_name,json=emotion1Name,proto3" json:"emotion_1_name,omitempty"`
	Emotion_1Rating float64                `protobuf:"fixed64,2,opt,name=emotion_1_rating,json=emotion1Rating,proto3" json:"emotion_1_rating,omitempty"`
	Emotion_2Name   string                 `protobuf:"bytes,3,opt,name=emotion_2_name,json=emotion2Name,proto3" json:"emotion_2_name,omitempty"`
	Emotion_2Rating float64                `protobuf:"fixed64,4,opt,name=emotion_2_rating,json=emotion2Rating,proto3" json:"emotion_2_rating,omitempty"`
	EyeMovement     string                 `protobuf:"bytes,5,opt,name=eye_movement,json=eyeMovement,proto3" json:"eye_movement,omitempty"`
	VoiceTension    string                 `protobuf:"bytes,6,opt,name=voice_tension,json=voiceTension,proto3" json:"voice_tension,omitempty"`
	BlinkFrequency  string                 `protobuf:"bytes,7,opt,name=blink_frequency,json=blinkFrequency,proto3" json:"blink_frequency,omitempty"`
	AccuracyRate    float64                `protobuf:"fixed64,8,opt,name=accuracy_rate,json=accuracyRate,proto3" json:"accuracy_rate,omitempty"`
	ConfidenceRate  float64                `protobuf:"fixed64,9,opt,name=confidence_rate,json=confidenceRate,proto3" json:"confidence_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResultAnalysis) Reset() {
	*x = ResultAnalysis{}
	mi := &file_userpb_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAnalysis) ProtoMessage() {}

func (x *ResultAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAnalysis.ProtoReflect.Descriptor instead.
func (*ResultAnalysis) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{11}
}

func (x *ResultAnalysis) GetEmotion_1Name() string {
	if x != nil {
		return x.Emotion_1Name
	}
	return ""
}

func (x *ResultAnalysis) GetEmotion_1Rating() float64 {
	if x != nil {
		return x.Emotion_1Rating
	}
	return 0
}

func (x *ResultAnalysis) GetEmotion_2Name() string {
	if x != nil {
		return x.Emotion_2Name
	}
	return ""
}

func (x *ResultAnalysis) GetEmotion_2Rating() float64 {
	if x != nil {
		return x.Emotion_2Rating
	}
	return 0
}

func (x *ResultAnalysis) GetEyeMovement() string {
	if x != nil {
		return x.EyeMovement
	}
	return ""
}

func (x *ResultAnalysis) GetVoiceTension() string {
	if x != nil {
		return x.VoiceTension
	}
	return ""
}

func (x *ResultAnalysis) GetBlinkFrequency() string {
	if x != nil {
		return x.BlinkFrequency
	}
	return ""
}

func (x *ResultAnalysis) GetAccuracyRate() float64 {
	if x != nil {
		return x.AccuracyRate
	}
	return 0
}

func (x *ResultAnalysis) GetConfidenceRate() float64 {
	if x != nil {
		return x.ConfidenceRate
	}
	return 0
}

type AiSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiSummary) Reset() {
	*x = AiSummary{}
	mi := &file_userpb_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiSummary) ProtoMessage() {}

func (x *AiSummary) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiSummary.ProtoReflect.Descriptor instead.
func (*AiSummary) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{12}
}

func (x *AiSummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type AiRecommendations struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Point_1Title       string                 `protobuf:"bytes,1,opt,name=point_1_title,json=point1Title,proto3" json:"point_1_title,omitempty"`
	Point_1Description string                 `protobuf:"bytes,2,opt,name=point_1_description,json=point1Description,proto3" json:"point_1_description,omitempty"`
	Point_2Title       string                 `protobuf:"bytes,3,opt,name=point_2_title,json=point2Title,proto3" json:"point_2_title,omitempty"`
	Point_2Description string                 `protobuf:"bytes,4,opt,name=point_2_description,json=point2Description,proto3" json:"point_2_description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AiRecommendations) Reset() {
	*x = AiRecommendations{}
	mi := &file_userpb_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiRecommendations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiRecommendations) ProtoMessage() {}

func (x *AiRecommendations) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiRecommendations.ProtoReflect.Descriptor instead.
func (*AiRecommendations) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{13}
}

func (x *AiRecommendations) GetPoint_1Title() string {
	if x != nil {
		return x.Point_1Title
	}
	return ""
}

func (x *AiRecommendations) GetPoint_1Description() string {
	if x != nil {
		return x.Point_1Description
	}
	return ""
}

func (x *AiRecommendations) GetPoint_2Title() string {
	if x != nil {
		return x.Point_2Title
	}
	return ""
}

func (x *AiRecommendations) GetPoint_2Description() string {
	if x != nil {
		return x.Point_2Description
	}
	return ""
}

type UserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nickname       string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age            int64                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,4,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	Height         int64                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Weight         float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Gender         string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_userpb_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserResponse) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserResponse) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *UserResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UserResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UserResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type ProfileCompletenessResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IsCompleted         bool                   `protobuf:"varint,1,opt,name=isCompleted,proto3" json:"isCompleted,omitempty"`
	PercentageCompleted float64                `protobuf:"fixed64,2,opt,name=percentage_completed,json=percentageCompleted,proto3" json:"percentage_completed,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProfileCompletenessResponse) Reset() {
	*x = ProfileCompletenessResponse{}
	mi := &file_userpb_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileCompletenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileCompletenessResponse) ProtoMessage() {}

func (x *ProfileCompletenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileCompletenessResponse.ProtoReflect.Descriptor instead.
func (*ProfileCompletenessResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{15}
}

func (x *ProfileCompletenessResponse) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *ProfileCompletenessResponse) GetPercentageCompleted() float64 {
	if x != nil {
		return x.PercentageCompleted
	}
	return 0
}

func (x *ProfileCompletenessResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NameAndPictureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,2,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NameAndPictureResponse) Reset() {
	*x = NameAndPictureResponse{}
	mi := &file_userpb_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameAndPictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameAndPictureResponse) ProtoMessage() {}

func (x *NameAndPictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameAndPictureResponse.ProtoReflect.Descriptor instead.
func (*NameAndPictureResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{16}
}

func (x *NameAndPictureResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NameAndPictureResponse) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

type GetEmotionalTrendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trends        []*DailyEmotion        `protobuf:"bytes,1,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmotionalTrendsResponse) Reset() {
	*x = GetEmotionalTrendsResponse{}
	mi := &file_userpb_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmotionalTrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmotionalTrendsResponse) ProtoMessage() {}

func (x *GetEmotionalTrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmotionalTrendsResponse.ProtoReflect.Descriptor instead.
func (*GetEmotionalTrendsResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetEmotionalTrendsResponse) GetTrends() []*DailyEmotion {
	if x != nil {
		return x.Trends
	}
	return nil
}

type GetDailyInsightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Insight       string                 `protobuf:"bytes,1,opt,name=insight,proto3" json:"insight,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"` // ADD THIS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyInsightResponse) Reset() {
	*x = GetDailyInsightResponse{}
	mi := &file_userpb_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyInsightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyInsightResponse) ProtoMessage() {}

func (x *GetDailyInsightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyInsightResponse.ProtoReflect.Descriptor instead.
func (*GetDailyInsightResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetDailyInsightResponse) GetInsight() string {
	if x != nil {
		return x.Insight
	}
	return ""
}

func (x *GetDailyInsightResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type GetReportsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*ReportSummary       `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,4,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportsListResponse) Reset() {
	*x = GetReportsListResponse{}
	mi := &file_userpb_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportsListResponse) ProtoMessage() {}

func (x *GetReportsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportsListResponse.ProtoReflect.Descriptor instead.
func (*GetReportsListResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetReportsListResponse) GetReports() []*ReportSummary {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *GetReportsListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetReportsListResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetReportsListResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

type GetReportDraftInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PatientName     string                 `protobuf:"bytes,1,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	ProjectedNextId string                 `protobuf:"bytes,2,opt,name=projected_next_id,json=projectedNextId,proto3" json:"projected_next_id,omitempty"` // We call it 'projected' because it might change!
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetReportDraftInfoResponse) Reset() {
	*x = GetReportDraftInfoResponse{}
	mi := &file_userpb_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportDraftInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportDraftInfoResponse) ProtoMessage() {}

func (x *GetReportDraftInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportDraftInfoResponse.ProtoReflect.Descriptor instead.
func (*GetReportDraftInfoResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetReportDraftInfoResponse) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *GetReportDraftInfoResponse) GetProjectedNextId() string {
	if x != nil {
		return x.ProjectedNextId
	}
	return ""
}

type ReportGeneratedResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResultAnalysis    *ResultAnalysis        `protobuf:"bytes,1,opt,name=result_analysis,json=resultAnalysis,proto3" json:"result_analysis,omitempty"`
	AiSummary         *AiSummary             `protobuf:"bytes,2,opt,name=ai_summary,json=aiSummary,proto3" json:"ai_summary,omitempty"`
	AiRecommendations *AiRecommendations     `protobuf:"bytes,3,opt,name=ai_recommendations,json=aiRecommendations,proto3" json:"ai_recommendations,omitempty"`
	Message           string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReportGeneratedResponse) Reset() {
	*x = ReportGeneratedResponse{}
	mi := &file_userpb_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportGeneratedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportGeneratedResponse) ProtoMessage() {}

func (x *ReportGeneratedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportGeneratedResponse.ProtoReflect.Descriptor instead.
func (*ReportGeneratedResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{21}
}

func (x *ReportGeneratedResponse) GetResultAnalysis() *ResultAnalysis {
	if x != nil {
		return x.ResultAnalysis
	}
	return nil
}

func (x *ReportGeneratedResponse) GetAiSummary() *AiSummary {
	if x != nil {
		return x.AiSummary
	}
	return nil
}

func (x *ReportGeneratedResponse) GetAiRecommendations() *AiRecommendations {
	if x != nil {
		return x.AiRecommendations
	}
	return nil
}

func (x *ReportGeneratedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetReportDetailsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReportId         string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	PatientName      string                 `protobuf:"bytes,2,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	AnalysisResult   *structpb.Struct       `protobuf:"bytes,3,opt,name=analysis_result,json=analysisResult,proto3" json:"analysis_result,omitempty"`
	ConfidenceResult float64                `protobuf:"fixed64,4,opt,name=confidence_result,json=confidenceResult,proto3" json:"confidence_result,omitempty"`
	AccuracyResult   float64                `protobuf:"fixed64,5,opt,name=accuracy_result,json=accuracyResult,proto3" json:"accuracy_result,omitempty"`
	Date             string                 `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Time             string                 `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetReportDetailsResponse) Reset() {
	*x = GetReportDetailsResponse{}
	mi := &file_userpb_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportDetailsResponse) ProtoMessage() {}

func (x *GetReportDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetReportDetailsResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetReportDetailsResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *GetReportDetailsResponse) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *GetReportDetailsResponse) GetAnalysisResult() *structpb.Struct {
	if x != nil {
		return x.AnalysisResult
	}
	return nil
}

func (x *GetReportDetailsResponse) GetConfidenceResult() float64 {
	if x != nil {
		return x.ConfidenceResult
	}
	return 0
}

func (x *GetReportDetailsResponse) GetAccuracyResult() float64 {
	if x != nil {
		return x.AccuracyResult
	}
	return 0
}

func (x *GetReportDetailsResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetReportDetailsResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_userpb_user_proto protoreflect.FileDescriptor

const file_userpb_user_proto_rawDesc = "" +
	"\n" +
	"\x11userpb/user.proto\x12\x04user\x1a\x1cgoogle/protobuf/struct.proto\"@\n" +
	"\x11CreateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"'\n" +
	"\vApiResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9d\x01\n" +
	"\x1bUploadProfilePictureRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12%\n" +
	"\x0efile_extension\x18\x04 \x01(\tR\rfileExtension\"\xb9\x01\n" +
	"\x14ProfileUpdateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x03R\x03age\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x03R\x06height\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\"\x18\n" +
	"\x16GetGlobalTrendsRequest\"k\n" +
	"\x16CreateNewReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\taudio_url\x18\x02 \x01(\tR\baudioUrl\x12\x1b\n" +
	"\tvideo_url\x18\x03 \x01(\tR\bvideoUrl\"3\n" +
	"\x14GetReportByIdRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"}\n" +
	"\x15GetReportsListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12!\n" +
	"\fsearch_query\x18\x04 \x01(\tR\vsearchQuery\"\xc0\x01\n" +
	"\fDailyEmotion\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x10\n" +
	"\x03joy\x18\x03 \x01(\x01R\x03joy\x12\x14\n" +
	"\x05anger\x18\x04 \x01(\x01R\x05anger\x12\x18\n" +
	"\asadness\x18\x05 \x01(\x01R\asadness\x12\x12\n" +
	"\x04fear\x18\x06 \x01(\x01R\x04fear\x12\x1a\n" +
	"\bsurprise\x18\a \x01(\x01R\bsurprise\x12\x18\n" +
	"\adisgust\x18\b \x01(\x01R\adisgust\"\xe3\x02\n" +
	"\rReportSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpatient_name\x18\x02 \x01(\tR\vpatientName\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1f\n" +
	"\vreport_type\x18\x04 \x01(\tR\n" +
	"reportType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04time\x18\x06 \x01(\tR\x04time\x12(\n" +
	"\raccuracy_rate\x18\a \x01(\x01H\x00R\faccuracyRate\x88\x01\x01\x12,\n" +
	"\x0fconfidence_rate\x18\b \x01(\x01H\x01R\x0econfidenceRate\x88\x01\x01\x12,\n" +
	"\x0fanalysis_result\x18\t \x01(\tH\x02R\x0eanalysisResult\x88\x01\x01B\x10\n" +
	"\x0e_accuracy_rateB\x12\n" +
	"\x10_confidence_rateB\x12\n" +
	"\x10_analysis_result\"\xef\x02\n" +
	"\x0eResultAnalysis\x12$\n" +
	"\x0eemotion_1_name\x18\x01 \x01(\tR\femotion1Name\x12(\n" +
	"\x10emotion_1_rating\x18\x02 \x01(\x01R\x0eemotion1Rating\x12$\n" +
	"\x0eemotion_2_name\x18\x03 \x01(\tR\femotion2Name\x12(\n" +
	"\x10emotion_2_rating\x18\x04 \x01(\x01R\x0eemotion2Rating\x12!\n" +
	"\feye_movement\x18\x05 \x01(\tR\veyeMovement\x12#\n" +
	"\rvoice_tension\x18\x06 \x01(\tR\fvoiceTension\x12'\n" +
	"\x0fblink_frequency\x18\a \x01(\tR\x0eblinkFrequency\x12#\n" +
	"\raccuracy_rate\x18\b \x01(\x01R\faccuracyRate\x12'\n" +
	"\x0fconfidence_rate\x18\t \x01(\x01R\x0econfidenceRate\"%\n" +
	"\tAiSummary\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\"\xbb\x01\n" +
	"\x11AiRecommendations\x12\"\n" +
	"\rpoint_1_title\x18\x01 \x01(\tR\vpoint1Title\x12.\n" +
	"\x13point_1_description\x18\x02 \x01(\tR\x11point1Description\x12\"\n" +
	"\rpoint_2_title\x18\x03 \x01(\tR\vpoint2Title\x12.\n" +
	"\x13point_2_description\x18\x04 \x01(\tR\x11point2Description\"\xc1\x01\n" +
	"\fUserResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x03R\x03age\x12'\n" +
	"\x0fprofile_picture\x18\x04 \x01(\tR\x0eprofilePicture\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x03R\x06height\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\"\x86\x01\n" +
	"\x1bProfileCompletenessResponse\x12 \n" +
	"\visCompleted\x18\x01 \x01(\bR\visCompleted\x121\n" +
	"\x14percentage_completed\x18\x02 \x01(\x01R\x13percentageCompleted\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"U\n" +
	"\x16NameAndPictureResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fprofile_picture\x18\x02 \x01(\tR\x0eprofilePicture\"H\n" +
	"\x1aGetEmotionalTrendsResponse\x12*\n" +
	"\x06trends\x18\x01 \x03(\v2\x12.user.DailyEmotionR\x06trends\"M\n" +
	"\x17GetDailyInsightResponse\x12\x18\n" +
	"\ainsight\x18\x01 \x01(\tR\ainsight\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails\"\xac\x01\n" +
	"\x16GetReportsListResponse\x12-\n" +
	"\areports\x18\x01 \x03(\v2\x13.user.ReportSummaryR\areports\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x04 \x01(\x05R\vcurrentPage\"k\n" +
	"\x1aGetReportDraftInfoResponse\x12!\n" +
	"\fpatient_name\x18\x01 \x01(\tR\vpatientName\x12*\n" +
	"\x11projected_next_id\x18\x02 \x01(\tR\x0fprojectedNextId\"\xea\x01\n" +
	"\x17ReportGeneratedResponse\x12=\n" +
	"\x0fresult_analysis\x18\x01 \x01(\v2\x14.user.ResultAnalysisR\x0eresultAnalysis\x12.\n" +
	"\n" +
	"ai_summary\x18\x02 \x01(\v2\x0f.user.AiSummaryR\taiSummary\x12F\n" +
	"\x12ai_recommendations\x18\x03 \x01(\v2\x17.user.AiRecommendationsR\x11aiRecommendations\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x9a\x02\n" +
	"\x18GetReportDetailsResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12!\n" +
	"\fpatient_name\x18\x02 \x01(\tR\vpatientName\x12@\n" +
	"\x0fanalysis_result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0eanalysisResult\x12+\n" +
	"\x11confidence_result\x18\x04 \x01(\x01R\x10confidenceResult\x12'\n" +
	"\x0faccuracy_result\x18\x05 \x01(\x01R\x0eaccuracyResult\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\b \x01(\tR\x04time2\x89\b\n" +
	"\vUserService\x128\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x11.user.ApiResponse\x123\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponse\x12;\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.ProfileUpdateRequest\x1a\x11.user.ApiResponse\x12L\n" +
	"\x14UploadProfilePicture\x12!.user.UploadProfilePictureRequest\x1a\x11.user.ApiResponse\x12Q\n" +
	"\x16GetProfileCompleteness\x12\x14.user.GetUserRequest\x1a!.user.ProfileCompletenessResponse\x12G\n" +
	"\x11GetPictureAndName\x12\x14.user.GetUserRequest\x1a\x1c.user.NameAndPictureResponse\x12Z\n" +
	"\x18GetGlobalEmotionalTrends\x12\x1c.user.GetGlobalTrendsRequest\x1a .user.GetEmotionalTrendsResponse\x12F\n" +
	"\x0fGetDailyInsight\x12\x14.user.GetUserRequest\x1a\x1d.user.GetDailyInsightResponse\x12C\n" +
	"\vUploadAudio\x12!.user.UploadProfilePictureRequest\x1a\x11.user.ApiResponse\x12C\n" +
	"\vUploadVideo\x12!.user.UploadProfilePictureRequest\x1a\x11.user.ApiResponse\x12N\n" +
	"\x0fCreateNewReport\x12\x1c.user.CreateNewReportRequest\x1a\x1d.user.ReportGeneratedResponse\x12K\n" +
	"\x0eGetReportsList\x12\x1b.user.GetReportsListRequest\x1a\x1c.user.GetReportsListResponse\x12L\n" +
	"\x12GetReportDraftInfo\x12\x14.user.GetUserRequest\x1a .user.GetReportDraftInfoResponse\x12K\n" +
	"\rGetReportByID\x12\x1a.user.GetReportByIdRequest\x1a\x1e.user.GetReportDetailsResponseB\x15Z\x13e_veda/proto/userpbb\x06proto3"

var (
	file_userpb_user_proto_rawDescOnce sync.Once
	file_userpb_user_proto_rawDescData []byte
)

func file_userpb_user_proto_rawDescGZIP() []byte {
	file_userpb_user_proto_rawDescOnce.Do(func() {
		file_userpb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userpb_user_proto_rawDesc), len(file_userpb_user_proto_rawDesc)))
	})
	return file_userpb_user_proto_rawDescData
}

var file_userpb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_userpb_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),           // 0: user.CreateUserRequest
	(*ApiResponse)(nil),                 // 1: user.ApiResponse
	(*GetUserRequest)(nil),              // 2: user.GetUserRequest
	(*UploadProfilePictureRequest)(nil), // 3: user.UploadProfilePictureRequest
	(*ProfileUpdateRequest)(nil),        // 4: user.ProfileUpdateRequest
	(*GetGlobalTrendsRequest)(nil),      // 5: user.GetGlobalTrendsRequest
	(*CreateNewReportRequest)(nil),      // 6: user.CreateNewReportRequest
	(*GetReportByIdRequest)(nil),        // 7: user.GetReportByIdRequest
	(*GetReportsListRequest)(nil),       // 8: user.GetReportsListRequest
	(*DailyEmotion)(nil),                // 9: user.DailyEmotion
	(*ReportSummary)(nil),               // 10: user.ReportSummary
	(*ResultAnalysis)(nil),              // 11: user.ResultAnalysis
	(*AiSummary)(nil),                   // 12: user.AiSummary
	(*AiRecommendations)(nil),           // 13: user.AiRecommendations
	(*UserResponse)(nil),                // 14: user.UserResponse
	(*ProfileCompletenessResponse)(nil), // 15: user.ProfileCompletenessResponse
	(*NameAndPictureResponse)(nil),      // 16: user.NameAndPictureResponse
	(*GetEmotionalTrendsResponse)(nil),  // 17: user.GetEmotionalTrendsResponse
	(*GetDailyInsightResponse)(nil),     // 18: user.GetDailyInsightResponse
	(*GetReportsListResponse)(nil),      // 19: user.GetReportsListResponse
	(*GetReportDraftInfoResponse)(nil),  // 20: user.GetReportDraftInfoResponse
	(*ReportGeneratedResponse)(nil),     // 21: user.ReportGeneratedResponse
	(*GetReportDetailsResponse)(nil),    // 22: user.GetReportDetailsResponse
	(*structpb.Struct)(nil),             // 23: google.protobuf.Struct
}
var file_userpb_user_proto_depIdxs = []int32{
	9,  // 0: user.GetEmotionalTrendsResponse.trends:type_name -> user.DailyEmotion
	10, // 1: user.GetReportsListResponse.reports:type_name -> user.ReportSummary
	11, // 2: user.ReportGeneratedResponse.result_analysis:type_name -> user.ResultAnalysis
	12, // 3: user.ReportGeneratedResponse.ai_summary:type_name -> user.AiSummary
	13, // 4: user.ReportGeneratedResponse.ai_recommendations:type_name -> user.AiRecommendations
	23, // 5: user.GetReportDetailsResponse.analysis_result:type_name -> google.protobuf.Struct
	0,  // 6: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	2,  // 7: user.UserService.GetUser:input_type -> user.GetUserRequest
	4,  // 8: user.UserService.UpdateUser:input_type -> user.ProfileUpdateRequest
	3,  // 9: user.UserService.UploadProfilePicture:input_type -> user.UploadProfilePictureRequest
	2,  // 10: user.UserService.GetProfileCompleteness:input_type -> user.GetUserRequest
	2,  // 11: user.UserService.GetPictureAndName:input_type -> user.GetUserRequest
	5,  // 12: user.UserService.GetGlobalEmotionalTrends:input_type -> user.GetGlobalTrendsRequest
	2,  // 13: user.UserService.GetDailyInsight:input_type -> user.GetUserRequest
	3,  // 14: user.UserService.UploadAudio:input_type -> user.UploadProfilePictureRequest
	3,  // 15: user.UserService.UploadVideo:input_type -> user.UploadProfilePictureRequest
	6,  // 16: user.UserService.CreateNewReport:input_type -> user.CreateNewReportRequest
	8,  // 17: user.UserService.GetReportsList:input_type -> user.GetReportsListRequest
	2,  // 18: user.UserService.GetReportDraftInfo:input_type -> user.GetUserRequest
	7,  // 19: user.UserService.GetReportByID:input_type -> user.GetReportByIdRequest
	1,  // 20: user.UserService.CreateUser:output_type -> user.ApiResponse
	14, // 21: user.UserService.GetUser:output_type -> user.UserResponse
	1,  // 22: user.UserService.UpdateUser:output_type -> user.ApiResponse
	1,  // 23: user.UserService.UploadProfilePicture:output_type -> user.ApiResponse
	15, // 24: user.UserService.GetProfileCompleteness:output_type -> user.ProfileCompletenessResponse
	16, // 25: user.UserService.GetPictureAndName:output_type -> user.NameAndPictureResponse
	17, // 26: user.UserService.GetGlobalEmotionalTrends:output_type -> user.GetEmotionalTrendsResponse
	18, // 27: user.UserService.GetDailyInsight:output_type -> user.GetDailyInsightResponse
	1,  // 28: user.UserService.UploadAudio:output_type -> user.ApiResponse
	1,  // 29: user.UserService.UploadVideo:output_type -> user.ApiResponse
	21, // 30: user.UserService.CreateNewReport:output_type -> user.ReportGeneratedResponse
	19, // 31: user.UserService.GetReportsList:output_type -> user.GetReportsListResponse
	20, // 32: user.UserService.GetReportDraftInfo:output_type -> user.GetReportDraftInfoResponse
	22, // 33: user.UserService.GetReportByID:output_type -> user.GetReportDetailsResponse
	20, // [20:34] is the sub-list for method output_type
	6,  // [6:20] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_userpb_user_proto_init() }
func file_userpb_user_proto_init() {
	if File_userpb_user_proto != nil {
		return
	}
	file_userpb_user_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userpb_user_proto_rawDesc), len(file_userpb_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userpb_user_proto_goTypes,
		DependencyIndexes: file_userpb_user_proto_depIdxs,
		MessageInfos:      file_userpb_user_proto_msgTypes,
	}.Build()
	File_userpb_user_proto = out.File
	file_userpb_user_proto_goTypes = nil
	file_userpb_user_proto_depIdxs = nil
}
