services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend_net

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    environment:
      - IAM_SERVICE_URL=iam-service:50052
      - USER_SERVICE_URL=user-service:50051
    ports:
      - "8080:8080"
    networks:
      - frontend_net
      - backend_net
    depends_on:
      - iam-service
      - user-service

  # -------------------------------------
  # Microservices
  # -------------------------------------
  iam-service:
    build:
      context: .
      dockerfile: iam-service/Dockerfile
    environment:
      # Pulls the common variable from your .env file
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis:6379
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASS=
    ports:
      - "50052:50052"
    networks:
      - backend_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      # Pulls the common variable from your .env file
      - DATABASE_URL=${DATABASE_URL}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "50051:50051"
    networks:
      - backend_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # -------------------------------------
  # Storage
  # -------------------------------------
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000" # MinIO API Port (Used by your Go and Python services)
      - "9001:9001" # MinIO Web Console Port (Used for manual viewing/management)
    networks:
      - backend_net
      - frontend_net
    volumes:
      - minio_data:/data
    # The command starts the server and assigns the console to port 9001
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - backend_net
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/e-veda-profiles || true;
      mc anonymous set download myminio/e-veda-profiles;
      exit 0;
      "

# -------------------------------------
# Networks & Volumes
# -------------------------------------
networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge
    internal: true

volumes:
  minio_data: # Persists MinIO data across container restarts
    driver: local