# Application Name = E_VEDA-GATEWAY
spring.application.name=E_VEDA-GATEWAY

# To run on localhost-8080 sever port
server.port=8080

# Routing to API Module running on localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].id=api-route
spring.cloud.gateway.server.webmvc.routes[0].uri.=${API_APP_ROUTE:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/protected/**

jwt.secert = fa4527d9746eb33a1593579bb307e12cda106965b457a12a2fe0b80f3dea4f7057ac95c4c6f3629735bfc94d36951edbad27326673c7f9fb8858a754c971f948
jwt.token.expiration.milliseconds=3600000 
# 1hr