# Application Name = E_VEDA-GATEWAY
spring.application.name=E_VEDA-GATEWAY

# To run on localhost-8080 sever port
server.port=8080

# Routing to API Module running on localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].id=api-route
spring.cloud.gateway.server.webmvc.routes[0].uri.=${API_APP_ROUTE:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/**