// proto/iam.proto
syntax = "proto3";
package iam;
option go_package = "e_veda/proto/iampb";

service IAMService {
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc SignUp (SignUpRequest) returns (SignUpResponse);
  rpc ForgotPassword (ForgotPasswordRequest) returns (ApiResponse);
  rpc VerifyOtp (VerifyOtpRequest) returns (VerifyOtpResponse);
  rpc ResetPassword (ResetPasswordRequest) returns (ApiResponse);
  rpc ValidateToken (TokenRequest) returns (ValidationResponse);
  rpc DeleteUser (DeleteUserRequest) returns (ApiResponse);
  rpc UpdatePassword (ChangePasswordRequest) returns (ApiResponse);
}

message ForgotPasswordRequest {
  string email = 1;
}

message VerifyOtpRequest {
  string email = 1;
  string otp= 2;
}

message ResetPasswordRequest {
  string reset_token = 1;
  string new_password = 2;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message SignUpRequest {
  string email = 1;
  string password = 2;
}

message ChangePasswordRequest {
  string old_password = 1;
  string new_password = 2;
  string user_uuid = 3;
}

message LoginResponse {
  string token = 1;
}

message TokenRequest {
  string token = 1;
}

message DeleteUserRequest {
  string user_uuid = 1;
}

message ValidationResponse {
  bool is_valid = 1;
  string user_id = 2;
}

message SignUpResponse {
  string user_uuid = 1;
}

message VerifyOtpResponse {
  string reset_token = 1;
}

message ApiResponse {
  string message = 1;
}